index.js

Reformat with Prettier and add titles to the config ui.

Formatting & titles to the ui

---

README.md

Copy paste of comment from slack. Convo related to NMEA0183->SK->N2K AIS.

doc: note adding pgns to allowed tx list of ntg-1

---

conversions/ais.js
conversions/cogSOG.js
conversions/gps.js
index.js
package-lock.json
package.json

Waiting for merge of plugin api changes

[WIP] chore: update to use the latest plugin api

---

conversions/tanks.js

fix: saving configuration fails when there is no tank data in signalk

---

conversions/speed.js

Generate the speed through the water PGN from SignalK's navigation.speedThroughWater.

 feature: add Speed Through Water PGN

---

conversions/environmentParameters.js

To push environment.outside.pressure out using PGN 130311.

Added Atmospheric Pressure using Environmental Parameters PGN 130311.

---

conversions/attitude.js

feature: add support for attitude (127257)

---

index.js

Let's call it just 'Signal K to NMEA 2000'.

fix: plugin name in server ui

---

conversions/seaTemp.js

Add a new PGN (130310) to get environment water temp, air temp and air pressure

feature: add Sea/Air Temp PGN (130310)

---

index.js
test/battery_status_127508.js

This has been failing for a while, did not dig deeper
to see when the actual code change happened.

chore: fix failing test

---

conversions/ais.js

Fixes 
```
Cannot read property 'length' of undefined at hasAnyKeys (/home/pi/.signalk/node_modules/signalk-to-nmea2000/conversions/ais.js:379:52) 
at Object.callback (/home/pi/.signalk/node_modules/signalk-to-nmea2000/conversions/ais.js:61:25) 
at FullSignalK.app.signalk.on (/home/pi/.signalk/node_modules/signalk-to-nmea2000/index.js:238:55)
```

Ais delta guard

---

conversions/engineParameters.js

Should be "Boost Pressure", not "Boost Presure".

Fix typo in "Boost Pressure" PGN payload

---

.travis.yml
package.json

add nodeJs compatibility >= 10
fix issue #61

chore: nodeJs compatibility >= 10

---

conversions/leeway.js

Leeway PGN 128000

---

conversions/temperature.js

fix: spelling mistake in refrigerator

---

conversions/raymarineAlarms.js

Adds support for Raymarine alarms (i70, Raymarine buzzer, etc) for notifications.navigation.anchor and notifications.mob

feature: add support for Raymarine alarms (PGN 65288)

---

conversions/windTrueWater.js

Added conversion to send True Wind Angle (boat referenced).

Added TWA as option

---

package.json

Debug removed, github-create-release as devDependency.

Deps cleanup

---

conversions/humidity.js
conversions/pressure.js

feature: add humidity (130313) and pressure pressure

---

index.js

fix: reportOutputMessages code generating erros

---

conversions/navigationdata.js

Fix Path to the nextPoint Lat/Lon to comply with the other nmea0183 and n2k converters of signalk

Fix nextPoint Path

---

conversions/setdrift.js

Add Set/Drift conversion for PGN 129291

Add Set/Drift conversion

---

conversions/windTrueGround.js

Publish environment.wind.directionTrue and environment.wind.speedOverGround to NMEA2000

Wind True Ground
